CREATE SCHEMA IF NOT EXISTS PUBLIC;
CREATE SCHEMA IF NOT EXISTS app_public;
CREATE SCHEMA IF NOT EXISTS app_private;

--

CREATE extension IF NOT EXISTS "uuid-ossp" WITH SCHEMA PUBLIC;

CREATE extension IF NOT EXISTS "citext" WITH SCHEMA PUBLIC;

CREATE extension IF NOT EXISTS "pgcrypto" WITH SCHEMA PUBLIC;

CREATE extension IF NOT EXISTS "pg_trgm" WITH SCHEMA PUBLIC;


--

ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON functions FROM PUBLIC;
