CREATE SCHEMA IF NOT EXISTS public;

--
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA PUBLIC;

CREATE EXTENSION IF NOT EXISTS "citext" WITH SCHEMA PUBLIC;

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA PUBLIC;

--
-- ALTER DEFAULT privileges REVOKE EXECUTE ON functions FROM public;
