version: '3.7'

services:
  db:
    container_name: db
    restart: unless-stopped
    build:
      context: ./db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  graphql:
    container_name: graphql
    restart: unless-stopped
    image: graphile/postgraphile:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend
    environment:
      DATABASE_URL: "postgres://admin:password@db:5432/postgres"
    command: [
      "postgraphile",
      "--connection", "${DATABASE_URL}",
      "--port", "5000",
      "--schema", "app_public",
      "--retry-on-init-fail",
      "--dynamic-json",
      "--show-error-stack",
      "--extended-errors", "hint,detail,errcode",
      "--graphql", "/graphql",
      "--graphiql", "/graphiql",
      "--enhance-graphiql"
    ]

  pgadmin:
    container_name: pgadmin
    restart: unless-stopped
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped


networks:
  backend:
    name: backend

volumes:
  data:
  pgadmin:
